VAE:
  Model:
    enc_channels: [1, 32, 64, 128, 256]
    dec_channels: [256, 128, 64, 32, 1]
    latent_dim: 512
  Training:
    lr: 1.0e-4
    epochs: 100
    optimizer: 'adamw'  # Options: 'adam', 'adamw'

HybridAttention:
  d_model: 256
  n_head: 6
  kernel_sizes: # Kernel sizes for the adaptive convolution
    - 1
    - 3
    - 5
    - 7
  num_layers: 3
  mask: 
  use_reverse: True

Aggregation:
  n_head: 8

Data:
  length: 51
  RxTx_num: 6
  subcarrier_num: 2025

Dataset:
  data_root: '/root/bindingvolume/CSI_dataset_NYCU/'
  train&val_json_path: 'datas/NYCU/train&val.json'
  val_json_path: 'datas/NYCU/val.json'
  batch_size: 64
  num_workers: 24

TestDataset:
  test_data_root: '/root/bindingvolume/CSI_dataset_UNCC' # '/root/bindingvolume/CSI_dataset_UNCC'
  test_json_path: 'datas/UNCC/test.json' # '/root/workspace/CoWIP/datas/UNCC/test.json'
  mode: 'test'

Training:
  lr: 1.0e-5
  epochs: 100
  optimizer: 'adamw'  # Options: 'adam', 'adamw'
  vae_ckpt_path: 