Model:
  latent_dim: 512


Data:
  length: 51
  RxTx_num: 6
  subcarrier_num: 2025

Dataset:
  data_root: '/root/bindingvolume/CSI_dataset_UNCC/' # '/root/SSD/PiWiFi/NYCU'
  train&val_json_path: 'datas/UNCC/train&val.json'
  val_json_path: 'datas/UNCC/val.json'
  batch_size: 32
  num_workers: 8

TestDataset:
  # NYCU
  test_data_root: '/root/bindingvolume/CSI_dataset_UNCC/' # '/root/SSD/PiWiFi/NYCU'
  test_json_path: 'datas/UNCC/train&val.json'
  # UNCC
  # test_data_root: '/root/SSD/PiWiFi/UNCC' 
  # test_json_path: '/root/CoWIP/benchmark/Wi-Seg/datas/UNCC/test.json'
  mode: 'val'

Training:
  lr: 1.0e-4
  epochs: 20
  optimizer: 'adam'  # Options: 'adam', 'adamw'

Loss:
  JHM:
    k: 1
    b: 1
  PAF:
    k: 1
    b: 0.3